# MESSAGE LABELS
LABEL_INBOX = "INBOX"
LABEL_SPAM = "SPAM"
LABEL_TRASH = "TRASH"
LABEL_UNREAD = "UNREAD"
LABEL_STARRED = "STARRED"
LABEL_IMPORTANT = "IMPORTANT"
LABEL_CATEGORY_PERSONAL = "CATEGORY_PERSONAL"
LABEL_CATEGORY_SOCIAL = "CATEGORY_SOCIAL"
LABEL_CATEGORY_PROMOTIONS = "CATEGORY_PROMOTIONS"
LABEL_CATEGORY_UPDATES = "CATEGORY_UPDATES"
LABEL_CATEGORY_FORUMS = "CATEGORY_FORUMS"


# CONDITIONS
ALL = "all"
ANY = "any"
FROM = "from"
TO = "to"
SUBJECT = "subject"
DATE_RECEIVED = "date received"
CONTAINS = "contains"
DOES_NOT_CONTAIN = "does not contain"
EQUALS = "equals"
DOES_NOT_EQUAL = "does not equal"
LESS_THAN = "is less than"
GREATER_THAN = "is greater than"

CONDITION_APPLY_TYPES = [ALL, ANY]

CONDITION_FIELDS_STRING = [FROM, TO, SUBJECT]
CONDITION_PREDICATES_STRING = [CONTAINS, DOES_NOT_CONTAIN, EQUALS, DOES_NOT_EQUAL]

CONDITION_FIELDS_DATETIME = [DATE_RECEIVED]
CONDITION_PREDICATES_DATETIME = [LESS_THAN, GREATER_THAN]


# ACTIONS
MARK_AS_READ = "mark as read"
MARK_AS_UNREAD = "mark as unread"
MOVE_MESSAGE = "move message"

ACTION_TYPES = [MARK_AS_READ, MARK_AS_UNREAD, MOVE_MESSAGE]
ACTION_MOVE_DESTINATION = [
    LABEL_INBOX,
    LABEL_SPAM,
    LABEL_TRASH,
    LABEL_UNREAD,
    LABEL_STARRED,
    LABEL_IMPORTANT,
    LABEL_CATEGORY_PERSONAL,
    LABEL_CATEGORY_SOCIAL,
    LABEL_CATEGORY_PROMOTIONS,
    LABEL_CATEGORY_UPDATES,
    LABEL_CATEGORY_FORUMS
]
